<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows7.0</TargetFramework>
        <RootNamespace>EWB_Tracker</RootNamespace>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>assets\ewb-journal-logo.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SharedLibrary\SharedLibrary.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <None Remove="assets\ewb-journal-logo.png" />
      <Resource Include="assets\ewb-journal-logo.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <None Remove="assets\Shentox-Regular2.ttf" />
      <Resource Include="assets\Shentox-Regular2.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <None Remove="assets\ewb-journal-logo.ico" />
      <Resource Include="assets\ewb-journal-logo.ico" />
    </ItemGroup>

</Project>